language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"

# Command to install dependencies
install: pip install -r requirements.txt

# Add databases.
services:
  - postgresql
  - redis-server

# Command to run tests
script: python manage.py test