language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"

sudo: enabled

# Command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls

# Add databases.
services:
  - postgresql
  - redis-server

# Environment variables.
env:
  - DATABASE_URL=postgres:///$(whoami) REDIS_URL=redis://

# Command to run tests
script: coverage run manage.py test -v 2

after_success: coveralls